// <auto-generated />
namespace Maturidade_Online.Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adicionarPilar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicionarPilar));
        
        string IMigrationMetadata.Id
        {
            get { return "201612141834381_adicionar Pilar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
